### ISSUE TITLE
Runtime go1.x support

### ISSUE THREAD

**Issue by nam-truong-le** [newrelic/newrelic-lambda-cli#220]
## Summary

Is there any plan to support runtime go1.x? Thank you.

**Comment by johnsoncwb** [comment]
Hello guys, any update about that? we're dropping some projects in go cuz we can't bring them up.

**Comment by chaudharysaket** [comment]
Merged [PR](https://github.com/newrelic/newrelic-lambda-cli/pull/271) such that CLI can support al2023 or go1.x  
Some changes in[ layers repo](https://github.com/newrelic/newrelic-lambda-layers) is pending to be released and is blocked due to github actions migration. Expected to unblock in a day or two. Thank you so much for the feedback.

**Comment by chaudharysaket** [comment]
Now, go1.x is supported as [provided.al2023](https://github.com/newrelic/newrelic-lambda-cli/#:~:text=provided.al2-,provided.al2023,-python3.7)
